export const IS_DROP_DOWN_SHOW = 'IS_DROP_DOWNS_SHOW'
export const IS_TOGGLE_SIDEBAR = 'IS_TOGGLE_SIDEBAR'
export const IS_LOADED = 'IS_LOADED'
export const MENU_TOGGLE = 'MENU_TOGGLE'
export const FETCH_PAGES='FETCH_PAGES'
export const FETCH_PAGE='FETCH_PAGE'
export const FETCH_MENU='FETCH_MENU'

